### ISSUE TITLE
Game play: game startup phase

### ISSUE THREAD

**Issue by samamou** [KeeganWoods1/C345---Risk#13]
Provide a group of C++ classes that implements the startup phase following the official rules of the Warzone
game. This phase is composed of the following sequence:
1. The order of play of the players in the game is determined randomly.
2. All territories in the map are randomly assigned to players one by one in a round-robin fashion.
3. Players are given a number of initial armies (A), where A is:
• If 2 players, A=40
• If 3 players, A=35
• If 4 players, A=30
• If 5 players, A=25
These armies are placed in the reinforcement pool for each player. This must be implemented in a
function/method named **startupPhase()** in the game engine. You must deliver a driver that demonstrates that
(1) all territories in the map have been assigned to one and only one player; (2) Players are given a number of
armies which is put in their reinforcement pool. This must be implemented in a single .cpp/.h file duo named
**GameEngine.cpp/GameEngine.h.**

**Comment by KeeganWoods1** [comment]
Done and merged.
